import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "../components/card";
import Navbar from "../components/Navbar";
import Popup from "reactjs-popup";
import PopUpComp from "../components/PopUpComp";
// import CustomPopUp from "../components/CustomPopUp";
import { useEffect, useState } from "react";
import { useQuery, gql } from "@apollo/client";
import { onError } from "@apollo/client/link/error";
import { LOAD_MOVIES } from "../GraphQL/queries";

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);
  const { error, loading, data } = useQuery(LOAD_MOVIES);

  const [movies, setMovies] = useState([]);
  // const [modalMovie, setModalMovie] = useState();

  useEffect(() => {
    if (data) {
      setMovies(data?.characters?.results);
      console.log(data);
    }
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      {movies && movies.map((mov) => <Card movie={mov} />)}

      <footer className={styles.footer}>hello</footer>

      {/* <CustomPopUp open={modalOpen} movie={modalMovie} /> */}
    </div>
  );
}
